apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: addresspoolvalidationwebhook.metallb.io
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-metallb-io-v1alpha1-addresspool
  failurePolicy: Fail
  name: addresspoolvalidationwebhook.metallb.io
  sideEffects: None
  admissionReviewVersions:
  - v1
  - vibeta1
  rules:
  - apiGroups:
    - metallb.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - addresspools
