apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{.NameSpace}}'
  name: '{{.ConfigMapName}}'
data:
  config: |
    peers:
    - peer-address: {{ .Address }}
      peer-asn: {{ .ASN }}
      my-asn: {{ .MyASN }}
      {{ if ne .Port 0 }}
      peer-port: {{ .Port }}
      {{ end }}
      {{ if ne .HoldTime 0 }}
      hold-time: {{ $.HoldTime }}
      {{ end }}
      {{ if ne .SrcAddress "" }}
      source-address: {{ .SrcAddress }}
      {{ end }}
      {{ if ne .RouterID "" }}
      router-id: {{ .RouterID }}
      {{ end }}
      {{ if ne .Password "" }}
      password: {{ .Password }}
      {{ end }}
     {{ $sel_len := len .NodeSelectors }} {{ if gt $sel_len 0 }}
      node-selectors:
      {{ range $node := .NodeSelectors -}}
        {{ if $node.MatchLabels }}
         - match-labels:
        {{ end }}
       {{ if $node.MatchExpressions -}}
        - match-expressions:
          {{ range $expression := $node.MatchExpressions -}}
          - key: {{ $expression.Key }}
            operator: {{ $expression.Operator }}
            values: {{ $expression.Values }}
          {{ end -}}
       {{ end }}
      {{ end -}}
      {{ end }}
