apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: METALLB_BGP_TYPE
              value: "frr-k8s"
            - name: DEPLOY_SERVICEMONITORS
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: webhook-server
          env:
            - name: METALLB_BGP_TYPE
              value: "frr" # TODO: change to frr-k8s
