name: General

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+"

defaults:
  run:
    shell: bash
    working-directory: metallboperator

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.54.2
        args: --timeout=15m0s --verbose

  unit:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.20' ]
    name: Unit and Integration tests
    steps:
    - name: Checkout Metal LB Operator
      uses: actions/checkout@v2
      with:
        path: metallboperator
        fetch-depth: 0 # Fetch all history for all tags and branches

    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code

    - name: Verify manifests
      run: |
        make manifests
        git diff --exit-code

    - name: Verify bin dir
      run: |
        BIN_FILE="metallb-operator.yaml" make bin
        git diff --exit-code bin/

    - name: Unit and Integration Tests
      run: |
        export KUBECONFIG=${HOME}/.kube/config
        METALLB_BGP_TYPE=native make test
        METALLB_BGP_TYPE=frr DEPLOY_KUBE_RBAC_PROXIES=true make test
        METALLB_BGP_TYPE=frr-k8s DEPLOY_KUBE_RBAC_PROXIES=true make test
